title: Priyanka Gupta # your name (or website title) here
logo: "/images/WhatsApp Image 2021-11-15 at 8.54.35 PM.jpeg?raw=true" # your photo (or logo) here

description:
  <p align="center">
  <a href="https://www.linkedin.com/in/priyanka-gupta-849158a0/">LinkedIn</a> |
  <a href="https://github.com/Priyanka-Gupta2021">GitHub</a>
  </p>
  
  <p align="justify">
  Data Science Enthusiast
  <br><br>
  Manager-Analytics and Reporting 
  Goddres Pharmaceuticals
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
google_analytics: UA-145578661-1 # Google Analytics tracking ID
